[package]
name = "overbite"
version = "0.1.0"
authors = ["Cyle Ven Dawson <dawsonc623@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
